### ISSUE TITLE
Using ReplayKit  Capturing screen

### ISSUE THREAD

**Issue by Raj123456788** [valentingrigorean/apprtc-ios-xamarin#1]
Hello Friend,
                     Just happened to see that you have a new Bindings project but when I added it to my solution that has BroadcastActivity via replay kit. It does not show send any samples?

Please let me know if you have already tried this?

**Comment by Raj123456788** [comment]
@valentingrigorean : Can you please tell me how can I use the replay kit project working? Still stuck with the issue.

**Comment by valentingrigorean** [comment]
hey i just did the binding update and convert objectiv-c to c# https://webrtc.googlesource.com/src/+/refs/heads/master/examples/objc/AppRTCMobile/

**Comment by Raj123456788** [comment]
Hello, I am not able to understand your previous comment? You mean replace Webrtc.framework?Can you please update the project or give me steps if you tried broadcasting screen to Apprtc? I amwating for your response.

**Comment by valentingrigorean** [comment]
yes, i just update Webrtc.framework + API but you use replay kit I just didn't test it. you can look at the link I provider and do your self you just need to convert objective-c to C# and that is not that hard.
Good luck

**Comment by Raj123456788** [comment]
hey, sorry to bother you again. I am getting this error. Can you please guide me how to fix this error? Error MT5211: Native linking failed, undefined Objective-C class: RTCAudioSessionConfiguration. The symbol '_OBJC_CLASS_$_RTCAudioSessionConfiguration' could not be found in any of the libraries or frameworks linked with your application. (MT5211)

**Comment by Raj123456788** [comment]
It is now saying Live Broadcast has stopped  due to attempted to start an invalid broadcast session. If you have any info let me know.

**Comment by valentingrigorean** [comment]
hey, I didn't test Live Broadcast I can help you if you got an issue with binding himself like crashing or w/e.

**Comment by Raj123456788** [comment]
Hey, I got it broadcast working(only webrtc screenshare lasts for 1 min) with https://github.com/mesibo/mesibowebrtcframework old libraries before Mar 30th release. Can you try to get binding working? I just need to fix Binding errors. Here is my API Definition and Structs.cs

**Comment by Raj123456788** [comment]
Sorry for the clutter above. I see difference in the apprtc-ios-xamarin vs apprtc-ios-xamarin-new
apprtc-ios-xamarin always worked with Broadcast: 
 RTCVideoSource source = _factory.VideoSource;

            var capturer = new ARDExternalSampleCapturer
            {
                Delegate = source
            };
            Delegate?.DidCreateLocalExternalSampleCapturer(this, capturer);

vs  apprtc-ios-xamarin-new :
 source = _factory.VideoSource;
            var capturer = new ARDExternalSampleCapturer(source); Delegate?.DidCreateLocalExternalSampleCapturer(capturer);

            return _factory.VideoTrackWithSource(source, _config.VideoTrackId);

//Can you please explain why we did not make a source with RTCVideoSource?
//Also: WHy was  IRTCVideoCapturerDelegate Delegate  vs IARDAppClientDelegate Delegate

**Comment by Raj123456788** [comment]
I think https://github.com/mesibo/mesibowebrtcframework  is the key to get screenbroadcast working. Please let me know your thoughts. Will wait for your answer.

**Comment by valentingrigorean** [comment]
hey i just post the last update binding i have. you can try now if you still have issue with binding himself you can leave a comment i will try to fix it.

**Comment by Raj123456788** [comment]
Hey, Thank you so much. But latest ioS library you added did not work. I guess for the screen broadcast you need a CustomVideoCapturer that Webrtc folks have not added. Now Mesibo has created their own codebase that has the custom video capture support. Now if you can please help me create bindings project for https://github.com/mesibo/mesibowebrtcframework it would be great. The binding project builds fine but the Apprtc.ios project throws errors when you build it. I am trying to create bindings via Sharpie and have not been successful. Thanks!

**Comment by Raj123456788** [comment]
Any luck with Mesibo Bindings?

**Comment by Raj123456788** [comment]
I got the bindings working. Thank you for help.
