### ISSUE TITLE
Iceserver Errors

### ISSUE THREAD

**Issue by Raj123456788** [valentingrigorean/apprtc-ios-xamarin#2]
I am trying to use signal it to my server and 
var response = await _httpClient.GetAsync(_url).ConfigureAwait(false); throws below error.

{StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.NSUrlSessionHandler+NSUrlSessionDataTaskStreamContent, Headers:
{
  Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048="…}

I tried using private void RequestTURNServersWithURL(
            NSUrl requestUrl,
            Action<IList<RTCIceServer>> completionHandler)
        {
            Contract.Requires(requestUrl != null);
            Contract.Requires(!string.IsNullOrEmpty(requestUrl.AbsoluteString));
            var list = new List<RTCIceServer>();

            var request = new NSMutableUrlRequest(requestUrl);
            var options = new NSMutableDictionary
            {
                { (NSString)"user-agent",(NSString)"Mozilla/5.0" },
                { (NSString)"origin",(NSString)Config.RoomServerHostUrl }
            };
            request.Headers = options;

            request.SendAsyncRequest((response, data, error) =>
            {
                if (error != null)
                {
                    Debug.WriteLine("Unable to get TURN server.");
                    completionHandler?.Invoke(list);
                    return;
                }
                var dict = data.DictionaryWithJSONData();
                completionHandler?.Invoke(
                    dict == null ?
                    list : RTCIceServerUtils.ServersFromCEODJSONDictionary(dict));
            });
        }

from your last example it throws error.

**Comment by valentingrigorean** [comment]
Hey i update only the binding client it's not working i think u can check/convert code [from](https://webrtc.googlesource.com/src/+/refs/heads/master/examples/objc/AppRTCMobile/). I don't have time to do it
